spring:
  profiles:
    active: local
  doc:
    swagger-ui:
      url: /openapi-3.0.yml
  sql:
    init:
      continue-on-error: true
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
