openapi: 3.0.1
info:
  title: HelloTalk
  description: HelloTalk
  version: 0.0.1-SNAPSHOT
servers:
- url: http://localhost:8081
tags: []
paths:
  /api/v1/ht/user/:
    get:
      tags:
      - api
      summary: Get a user's details
      description: Get a user's details
      operationId: get-user
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-ht-user-486549215'
              examples:
                get-user:
                  value: "[{\"id\":\"1bfff94a-b70e-4b39-bd2a-be1c0f898589\",\"name\"\
                    :\"anyName\",\"dob\":\"anyDob\",\"gender\":\"anyGender\",\"selfIntroduction\"\
                    :\"anySelfIntroduction\",\"creationDate\":\"anyCreationDate\"\
                    ,\"status\":\"anyStatus\",\"handle\":\"anyHandle\",\"nativeLanguage\"\
                    :\"anyNativeLanguage\",\"targetLanguage\":\"anyTargetLanguage\"\
                    ,\"occupation\":\"anyOccupation\",\"placesToVisit\":\"anyPlacesToVisit\"\
                    ,\"subscriptionType\":\"anySubscriptionType\",\"hometown\":{\"\
                    id\":\"be4ec235-f425-4514-bb2c-119c5956fe15\",\"city\":\"anyCity\"\
                    ,\"country\":\"anyCountry\"},\"hobbyAndInterests\":[{\"id\":\"\
                    af3b0fba-2f5a-456e-9b08-c0e4b6f16da2\",\"title\":\"anyInterest\"\
                    }]}]"
components:
  schemas:
    api-v1-ht-user-486549215:
      type: object
