DELETE from followship;
DELETE from users_hobbies;
DELETE from comment;
DELETE from moment_tags;
DELETE from moment_like;
DELETE from moment;
delete from message;
DELETE from users;
DELETE from hometown;
