name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: ./mvnw clean package

    - name: Run unit tests
      run: ./mvnw test --fail-at-end -Dtest=*Test

    - name: Start PostgreSQL container
      run: docker run -d -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=helloTalk postgres

    - name: Run integration tests
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/helloTalk
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
      run: ./mvnw verify --fail-at-end -Dspring.profiles.active=test

