name: SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    container:
      image: sonarqube-scanner:latest
      options: --network host
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B clean package -DskipTests
      - name: SonarQube analysis
        run: sonar-scanner \
          -Dsonar.projectKey=com.example:HelloTalk \
          -Dsonar.projectName=HelloTalk \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sources=src \
          -Dsonar.java.binaries=target/classes \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
