name: SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  SONAR_HOST_URL: http://localhost:9000/

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests
      - name: SonarQube analysis
        uses: SonarSource/sonarqube-scan-action@v1
        with:
          projectBaseDir: ./
          entryPoint: com.example.hellotalk.HelloTalkApplication
          projectKey: com.example:HelloTalk
          projectName: HelloTalk
          sources: '.'
          extraProperties: |
            sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            sonar.java.binaries=target/classes
          sonar.host.url: ${{ env.SONAR_HOST_URL }}
          sonar.login: ${{ secrets.SONAR_TOKEN }}
