name: SonarQube Analysis

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw -B clean package
      - name: SonarQube analysis
        uses: SonarSource/sonarqube-scan-action@v1
        with:
          projectKey: com.example:HelloTalk
          projectName: HelloTalk
          sources: '.'
          extraProperties: |
            sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            sonar.java.binaries=target/classes
          sonar.login: ${{ secrets.SONAR_TOKEN }}
